### ISSUE TITLE
Como mudar rota do argumento de URL após o upload - NodeJS MVC.

### ISSUE THREAD

**Issue by smachs** [LacunaSoftware/RestPkiSamples#3]
Ola, após o envio do arquivo ao `public\app-data` o `upload.js` não está anexando minha rota ao argumento de URL de sucesso.

[https://i.imgur.com/Bcn5bNd.png](url)

```
res.render('company-parallel-and-branch', {
    token: token,
    sendFileManager: req.query.sendFileManager
});
```

Meus `require` dos módulos.
```
app.use('/upload', require('./digital-certificate/upload'));
app.use('/authentication', require('./digital-certificate/authentication'));
app.use('/pades-signature', require('./digital-certificate/pades-signature'));
app.use('/pades-signature-server-key', require('./digital-certificate/pades-signature-server-key'));
app.use('/cades-signature', require('./digital-certificate/cades-signature'));
app.use('/cades-signature-server-key', require('./digital-certificate/cades-signature-server-key'));
app.use('/xml-full-signature', require('./digital-certificate/xml-full-signature'));
app.use('/xml-element-signature', require('./digital-certificate/xml-element-signature'));
```
Rota que chama o template que estou fazendo o upload de arquivos em `form`.
```
api.get("/company-parallel-and-branch", function (req, res) {
  var path = __dirname + '/routes/company-parallel-and-branch/';
  res.sendFile(path + "company-parallel-and-branch.html");

  require('./digital-certificate/authentication');
  require('./digital-certificate/cades-signature');
});
```

Minha rota completa de `multipart/form-data`.
```
var express = require('express');
var request = require('request');
var fs = require('fs');
var uuid = require('node-uuid');
var path = require('path');
var multer = require('multer');

var upload = multer();
var router = express.Router();
var appRoot = process.cwd();

router.get('/', function(req, res, next) {
	res.render('upload');
});

router.post('/', upload.single('sendFileManager'), function(req, res, next) {
	var fileExt = path.extname(req.file.originalname);
	var filename = uuid.v4() + fileExt;
	
	var appDataPath = appRoot + '/public/app-data/';
	if (!fs.existsSync(appDataPath)){
		fs.mkdirSync(appDataPath);
	}
	
	fs.writeFileSync(appDataPath + filename, req.file.buffer);

	res.redirect(req.query.goto + '?sendFileManager=' + filename);
});

module.exports = router;
```

Otíma solução!!! E obrigado por futuros esclarecimentos estou a dias tentando resolver esse erro de argumento de URL indefinido...

**Comment by ismaelmedeiros** [comment]
Olá @smachs 
No nosso exemplo, a rota é passada como argumento para a rota de upload, por exemplo:

```
a(href=upload?goto=pades-signature) Create a signature with a file uploaded by user
```

Como se pode ver no arquivo [index.jade](https://github.com/LacunaSoftware/RestPkiSamples/blob/master/NodeJS/mvc/views/index.jade#L13-L16).

Esse argumento é usado na rota de upload da seguinte forma: `req.query.goto`

O problema que deve estar acontecendo é que a rota de upload está sendo chamado sem o argumento 
"?goto=".

**Comment by smachs** [comment]
@ismaelmedeiros tudo bem? xD haveria algum modo de invez da rota fazer a argumentação no url, a rota apenas faz o upload do arquivo e não utilizar o `res.redirect(req.query.goto + '?sendFileManager=' + filename);`? Exemplo: Após o cliente fazer o upload do arquivo, mantê-lo na mesma página que foi feito o upload e prosseguir com a certificação do documento sem o redirecionamento para outro template externo?

**Comment by ismaelmedeiros** [comment]
@smachs tudo bem?
O que realmente importa para assinatura é o conteúdo do arquivo, que irá ser assinado, codificado em _Base64_. 

No exemplo, é utilizada essa rota de upload separada simplesmente para fins de demonstração. Do que jeito que você está querendo, basta receber o conteúdo do arquivo que deseja ser assinado e enviar este conteúdo codificado em _Base64_ para a nosso serviço. 

Pode-se ver como é feito na rota [pades-signature.js](https://github.com/LacunaSoftware/RestPkiSamples/blob/master/NodeJS/mvc/routes/pades-signature.js#L40). Nesse exemplo, o arquivo, que foi armazenado em `public\app-data`, é lido e codificado para _Base64_. Bastaria fazer essa lógica na mesma rota em que é feito o upload, onde se recebe o conteúdo do arquivo pela primeira vez antes que comece o processo de assinatura.

**Comment by smachs** [comment]
@ismaelmedeiros consegui resolver a renderização de sucesso do upload com `res.redirect('/subscribe-file-with-cades' + '?sendFileManager=' + filename);` poderia me mostrar um exemplo de como extrair informações do arquivo enviado a pasta `public/app-data` para por exemplo em meu template `<p>Você está assinando <a href="/SampleDocument.pdf" target="_blank">esse documento.</a>` para que o cliente possa fazer a assinatura do documento via **CAdES**. 

Fiz upload da minha aplicação aqui no **Github** se quiser da uma olhada, agradeço :smile: 

[Rotas da certificação digital](https://github.com/smachs/famagas-itapetininga/tree/master/server/digital-certificate)
[Pagina de upload do arquivo para ser assinado](https://github.com/smachs/famagas-itapetininga/blob/a7795430568aa8f30a1be452aacc5fb96136a82b/server/routes/company-parallel-and-branch/company-parallel-and-branch.html#L985)
[Após upload do arquivo com sucesso chama cades-signature.html](https://github.com/smachs/famagas-itapetininga/blob/master/server/templates/cades-signature.html)

**Comment by alexswi** [comment]
Boa tarde smachs, 

Penso ser melhor você contatar diretamente o nosso suporte a desenvolvedores em [http://lacuna.help](http://lacuna.help) . Desse modo poderemos agendar um call para esclarecer melhor as suas dúvidas.

**Comment by smachs** [comment]
@alexswi Ok, irei contatar obrigado!
